version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      wordpress-scripts:
        patterns:
          - "@wordpress/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
